{% set version = "0.0.10" %}

package:
  name: ersilia
  version: {{ version }}

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - pip
    - wheel 
  run:
    - python

about:
  home: https://github.com/ersilia-os
  license: MIT
  summary: NA
  