name: ✍️ Outreachy Summer 24
description: Track your contribution period to Outreachy 2024
title: "✍️ Contribution period: <your_name> "
labels: [internship]

body:
  - type: markdown
    attributes:
      value: Welcome to Ersilia! Please use this issue to track your contributions to the Ersilia community for the Outreachy internship. Mark the tasks as you complete them!
  - type: checkboxes
    attributes:
      label: Week 1 - Get to know the community
      description: Please complete the following tasks and mark them once finished
      options:
      - label: Join the communication channels
        required: false
      - label: Open a GitHub issue (this one!)
        required: false
      - label: Install the Ersilia Model Hub and test the simplest model
        required: false
      - label: Install Docker if needed, and test another model
        required: false
      - label: Write a motivation statement to work at Ersilia
        required: false
      - label: Submit your first contribution to the Outreachy site
        required: false
  - type: checkboxes
    attributes:
      label: Week 2 - Get Familiar with Machine Learning for Chemistry
      description: Please complete the following tasks and mark them once finished
      options:
      - label: Select a model from the list suggested in GitBook
        required: false
      - label: Download and serve the model via the Ersilia Model Hub to ensure it works
        required: false
      - label: Open a repository on your GitHub user with all the necessary files
        required: false
      - label: Select and clean a dataset of 1000 molecules (example notebook 1)
        required: false
      - label: Run predictions for the molecules on the selected model and evaluate the results
        required: false
      - label: Run predictions for the molecules on the selected model and evaluate the results
        required: false
  - type: checkboxes
    attributes:
      label: Week 3 - Validate a Model in the Wild
      description: Please complete the following tasks and mark them once finished
      options:
      - label: Find a suitable dataset with sufficient experimental results
        required: false
      - label: Clean and standardize the dataset
        required: false
      - label: Run predictions and calculate metrics.
        required: false
  - type: checkboxes
    attributes:
      label: Week 4 - Prepare your final application
      description: Please complete the following tasks and mark them once finished
      options:
      - label: Submit the final application in the Outreachy website
        required: false
