name: Convert Back-end Airtable to CSV file

on:
  workflow_dispatch:

  schedule:
    - cron: '0 2 * * *' 

jobs:
  convert-airtable-to-csv:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # pin@v4.0.0

      - name: Install dependencies
        run:
          pip install airtable-python-wrapper

      - name: Convert to backend of Airtable to CSV
        env:
            AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
            AIRTABLE_BASE_ID: 'appgxpCzCDNyGjWc8'
            AIRTABLE_TABLE_NAME: 'Models'
        run: |
          python .github/scripts/convert_airtable_to_csv.py $AIRTABLE_API_KEY $AIRTABLE_BASE_ID $AIRTABLE_TABLE_NAME "models_from_airtable.csv"

      - name: Commit and push file
        uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772 # pin@v1.4
        with:
          author_name: "ersilia-bot"
          author_email: "ersilia-bot@users.noreply.github.com"
          message: "Update CSV file from Airtable [skip ci]"  
          repository: "${{ github.repository }}" 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          amend: true
          force: true
