name: Approve Command Trigger
on:
  issue_comment:
    types: [created]
jobs:
  approve-command-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Approve Command Trigger
        uses: peter-evans/slash-command-dispatch@a28ee6cd74d5200f99e247ebc7b365c03ae0ef3c # pin@v3.0.1
        with:
          token: ${{ secrets.PAT }}
          issue-type: issue
          permission: write
          reactions: false
          commands: |
            approve
