name: json syntax check

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: write # required to leave comments on pull requests

jobs:
  json-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v3.5.3

      - name: json syntax check
        uses: GrantBirki/json-yaml-validate@ce9d0c1ff859732d3839a5e1cdc22ff203aa464a # pin@v2.4.0
        with:
          exclude_file: ".github/config/exclude.txt" # .gitignore style file for exclusions
          comment: "true" # allow PR comments with error messages
