name: json syntax check

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: write # required to leave comments on pull requests

jobs:
  json-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v3.5.3

      - name: json syntax check
        uses: GrantBirki/json-yaml-validate@87b2d309a02f4942c5e602183eeea11008a640f9 # pin@v1.4.0
        with:
          exclude_file: ".github/config/exclude.txt" # .gitignore style file for exclusions
          comment: "true" # allow PR comments with error messages
