name: json syntax check

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: write # required to leave comments on pull requests

jobs:
  json-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # pin@v3.5.3

      - name: json syntax check
        uses: GrantBirki/json-yaml-validate@3add42f5fa8bfff04a3fe664d27a316736257ef1 # pin@v2.3.1
        with:
          exclude_file: ".github/config/exclude.txt" # .gitignore style file for exclusions
          comment: "true" # allow PR comments with error messages
