name: json syntax check

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: write # required to leave comments on pull requests

jobs:
  json-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3.5.2

      - name: json syntax check
        uses: GrantBirki/json-yaml-validate@78e22e5c6549059f267f96aea1aaf97132896c04 # pin@v1.3.0
        with:
          exclude_file: ".github/config/exclude.txt" # .gitignore style file for exclusions
          comment: "true" # allow PR comments with error messages
