name: Update a given model with current eos-template workflows
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      model_id:
        description: Model ID
        required: true
        type: string

env:
  MODEL_ID: ${{ github.event.inputs.model_id }}

job:
  update-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # pin@v3.5.0

      - name: Update model workflows using script
        run: |
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/update_model_workflows_from_template.py
          git lfs install
          python update_model_workflows_from_template $MODEL_ID