name: On new tag pushed
on:
  create

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Print new tag
      run: echo "New tag was pushed: ${{ env.TAG_NAME }}"
