name: Ersilia model output prediction
on:
  workflow_dispatch:
  # run the workflow every 2 hours
  # schedule:
  #  - cron: '30 */2 * * *'

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        count: [0, 1, 2, 3, 4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3.5.2

      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Source conda
        run: source $CONDA/etc/profile.d/conda.sh

      - name: Install dependencies
        run: |
          source activate
          conda init
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge

      - name: Install ersilia
        run: |
          source activate
          python --version
          echo "After conda init"
          conda init
          python -m pip install -e .[test]

      - name: Predict output
        run: |
          source activate
          MODEL_ID=$(ersilia sample --model)
          echo "Sample model id selected: $MODEL_ID"
          ersilia fetch $MODEL_ID
          ersilia serve $MODEL_ID
          ersilia sample -n 100 -f input.csv
          ersilia api -i input.csv -o output.csv
          ersilia close
