name: Update a given model with current eos-template workflows

on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      model_id:
        description: Model ID
        required: true
        type: string

env:
  MODEL_ID: ${{ github.event.inputs.model_id }}

jobs:
  update-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout persist credentials
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3.5.2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          lfs: 'true'

      - name: Update model workflows using script
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_ }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git lfs install
          git config --global github.user ${{ github.actor }}
          git config --global github.token $GITHUB_TOKEN
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/update_model_workflows_from_template.py
          python update_model_workflows_from_template.py $MODEL_ID
